travis:
  secure:
    BINSTAR_TOKEN: qOH24c+lkSeaQSU8nWlBKWe0RPjooMpljD1lWnVG8FzGOkFKEcRlprYv6bBJk72UqnXID5EkuAimvIZBLojqoSDGp4dBegO/kP/euJ9MWnr9EaM9nuMOVA0H7IoWOaHpzzdQf8dZNo9CYghyK0O78FMwW/3m6inTp4FjCauqyFX2Wvc2lPUUxrSHEhCDHV993ovKmXynv73uQu52Kh2VHjdGYeKzLf3LveFco0wYKnDytSQXY3dfTwb2knivVdZ/DBSNCyuGe5pERxxTMVGHBK4H0Bo2kszMUw0Z/aDXnVYmP43ZB69gzEwR3c4hWUVRDRUNeMrrFAqZZVLSLN+1nB3L6zQSVdr3NsJmDCIZg/NeBCGFUKe+0Vxc0wC4wPo99lzBflasHzf5HTddgKHqU4LajbA0nwvJxktxE8z/+8VWs5Fj/JgzNzdcgImalK6y/8d5pd2nvlQHhoDGifWJH0u1h1tR1UbDnfy3AQRt/rbsLt/8jXCL+B0Ez8JZeIZn/n3IR++7UbTyxcN+Z6gI9P07CcrA4mDXjiPzFb1cIeSv6cqOJoX4cBO3W/sJGzelltbf6GtOWcCQn9gS9QavZQWYBqzcAmJrwy++1CtS6ai7CVeLz3jtDj8Z5DU2Z011hURBf/PuX0xWsngQ29uZppreEPHOEjym6qvSBAFNnB0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
