travis:
  secure:
    BINSTAR_TOKEN: tSMUUQ1SMauwbOuLp9agAyc94Ha442pJVLKF4UQwtUjPVJtw4PXMqk8qVl4OlZBht9S0yRb9+zHk8LVpkEXqbZLxCbjruiBVdcdmHZ+jhhcrSYQYXuNjhXbUuT2/SAknowigz5nWnzacCpKfhr/95L06fWaMG663zLjdion4Zt2CIfZsVxS3yxeevbBVJdsHIbcLzFfmQzfnw43qTaBUUhssB+4zhduLtwJlnFSSazy5Zw9Li3sQXE+Fmnb2Kp2BCULbCYxWbbRtOiXaJOT7jS9CQ6PJEY4FGkcefymPBAsS53bCtJFBGlQXQIn3NM1B0CgbAccogttwkoxGDyz8EixlncEAyZn+bAeU6OSKnqt02qEmp7N46FOgTXnJgKvU5+sDlTyCPi2yM8i6XckwMQRziMpqWEWVXW+pj3qgj+1vvf8fqLx/aQO8u7WWQYm/weki9iIRTvMg2Xqjk52jz6r2ZkJmj3NYNLOZHwXDpTXMQi1YGYvDojJbIX3tx8hbZIvP4lrtn1uLfbo0aSVjoFUAEk3514JwOVozEhd5Ku9CwU8f6goM8faKvrilmngAUTMhv0AzZP/ESARG0QYPyV2XM+BqLt8PDl2AvzMacS82LOo53wMadaVnZv82iYXerfkVms9QwiBOfpT3PyMPe0C6+vBn+TaTzeTh+NHPpD0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
