travis:
  secure:
    BINSTAR_TOKEN: pvOOl05nGoFKNzY+/785LQbadyWiUjTyV6iQ/bIFMs3HJ6RNkz+GcGR3UiMLl8jAb27EWD+c0eIrEkphF02tPDysOvQGHkk9uxwKIYcK1T09QyM4DsUKiEODPyUfgji1jnfoLu6Ukxr7hfKendU5aJfUXPwcmhF0N0PoGevDB5kKg50XDFkHDNwWzrLCiqAoL1eJerfFGNamlEI8q1h3GflbO5Ga/0G0LYsy4oZMEmwZ0/x8QKT5kx9868Hp+/onuCYpIW19Cq3q0HA886CzuNSKiwgXJsL+7r58MWbc7YQcK4SxkA+d+aoCwK79ZffW4UtrgKj/4afeFT+hCKqbi1UOJI3jlcre4N4Ye09MEDKXClUZRF0yWJJvS/2RhFqhYeeyE7x1O6AI1YHV2wmoPVCXVp3Lk57PbRh0th/hLR0sKaWvaRorfVEjkxrDxo+go8lB+jX+bERHsifodBmXha6fsnt7P+vFJ2wwUuSBU/+usg83+wUuLK5hXsiiHA2Iy/U/mom23Q4S+zMOS2rQoKEgxgtNx3tgD01iSGV05G/2TWfhbFm0UhOg4RwFSFv/j1X5nSl//eo7U2CTzcrVtfJ/KdMl9FFMpjvrleMxTblR4S4tGhE2q7sLRxbcvfp8g7vIMLZE5QrNIcZcS+GUwRA/61TZZ5oQCXSLpxf0BAM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
